# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slv < Formula
  desc ""
  homepage "https://slv.sh"
  version "0.12.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amagioss/slv/releases/download/v0.12.1/slv_darwin_amd64.zip"
      sha256 "1b1a8c1c78f8654b1b1b02725ffcf4c73c510090aa1fd35ec0b736f6d9a5f7ce"

      def install
        bin.install "slv"
        generate_completions_from_executable(bin/"slv","completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amagioss/slv/releases/download/v0.12.1/slv_darwin_arm64.zip"
      sha256 "a20372d5380df85de6d41f14eb75e7065119474715879283bf13d919f97cebe2"

      def install
        bin.install "slv"
        generate_completions_from_executable(bin/"slv","completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/amagioss/slv/releases/download/v0.12.1/slv_linux_amd64.zip"
      sha256 "c2e380070488d235b93b830661b9b3b519d7e1dc1ed617ba2e2c6fa819aec71c"
      def install
        bin.install "slv"
        generate_completions_from_executable(bin/"slv","completion")
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/amagioss/slv/releases/download/v0.12.1/slv_linux_arm.zip"
      sha256 "547864417ec5a96bbe7335dd1a61db400aa5e5e7ae02969dd46387fbba30cd79"
      def install
        bin.install "slv"
        generate_completions_from_executable(bin/"slv","completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/amagioss/slv/releases/download/v0.12.1/slv_linux_arm64.zip"
      sha256 "b5bc79ee7003913faa74e28f932e412d35b95e39bf436d77ab8ba0d3d031432b"
      def install
        bin.install "slv"
        generate_completions_from_executable(bin/"slv","completion")
      end
    end
  end
end
