# This file was generated by GoReleaser. DO NOT EDIT.
cask "slv" do
  version "0.23.4"

  on_macos do
    on_intel do
      sha256 "d275247bbfec961af0a243f00ce0565c4341289bf192565eb88a2f517449057d"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_darwin_amd64.zip",
        verified: "github.com/amagioss/slv/"
    end
    on_arm do
      sha256 "a8ea3e70c24006c9cecd4666a5390c66fa249e963fef83ae6574c8e8ea0c126b"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_darwin_arm64.zip",
        verified: "github.com/amagioss/slv/"
    end
  end

  on_linux do
    on_intel do
      sha256 "4a23a2ffdefaef1d171f5c80869bfbeffa4ce46059513f49afd0d49b66081e2b"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_linux_amd64.zip",
        verified: "github.com/amagioss/slv/"
    end
    on_arm do
      sha256 "e914eb07dee5526f3ffffac7e3cdd13fa4dce90d3140ac6a73e73d0d1fea65b4"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_linux_arm64.zip",
        verified: "github.com/amagioss/slv/"
    end
  end

  name "slv"
  desc "SLV (Secure Local Vault) - Securely store, share, and access secrets alongside your codebase with modern encryption techniques."
  homepage "https://slv.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slv"]
    end
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/etc/bash_completion.d"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/zsh/site-functions"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/slv completion bash > #{HOMEBREW_PREFIX}/etc/bash_completion.d/slv"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/slv completion zsh > #{HOMEBREW_PREFIX}/share/zsh/site-functions/_slv"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/slv completion fish > #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/slv.fish"]
  end

  # No zap stanza required

end
