# This file was generated by GoReleaser. DO NOT EDIT.
cask "slv" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "slv"], chdir: "."
    end
  end

  version "0.23.11"

  on_macos do
    on_arm do
      sha256 "d07187f885c5de97a9dde69ece8b1e86f0954b59b503bf4da254aa74a392ed2c"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_darwin_arm64.zip"
    end
    on_intel do
      sha256 "229e028ad27633430a7dea34f4672aec3b0b65cc9199ddbde0b793cec32c6b02"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_darwin_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "91d9feb5ae91d40f6a293891166f685d7149af3dabe773b287b37d0bfc9609fe"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_linux_arm64.zip"
    end
    on_intel do
      sha256 "27d838d6f061f5404fe470ca030e90bbb43c59cf77878c28a841da40d6cb14b7"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_linux_amd64.zip"
    end
  end

  name "slv"
  desc "SLV (Secure Local Vault) - Securely store, share, and access secrets alongside your codebase with modern encryption techniques."
  homepage "https://slv.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slv"

  generate_completions_from_executable "slv",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
