# This file was generated by GoReleaser. DO NOT EDIT.
cask "slv" do
  version "0.23.7"

  on_macos do
    on_intel do
      sha256 "f7dfe378a91eb1b255cc22d93af2501ca47fc27bfe2219653b9c282b2bba0eae"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_darwin_amd64.zip",
        verified: "github.com/amagioss/slv/"
    end
    on_arm do
      sha256 "689fcc2fe1a7ff06282764651be2f0426304d826f2b055694ff24fd507c33f83"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_darwin_arm64.zip",
        verified: "github.com/amagioss/slv/"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b9ee1364d5c79a96a999281b813cb7385ec831042c45b9fdb04abd6c9c413cb"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_linux_amd64.zip",
        verified: "github.com/amagioss/slv/"
    end
    on_arm do
      sha256 "22090f620fb334f09178926b7d7efe1282c444baf7a72460a0ae5bd6b7afd6a5"
      url "https://github.com/amagioss/slv/releases/download/v#{version}/slv_linux_arm64.zip",
        verified: "github.com/amagioss/slv/"
    end
  end

  name "slv"
  desc "SLV (Secure Local Vault) - Securely store, share, and access secrets alongside your codebase with modern encryption techniques."
  homepage "https://slv.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slv"]
    end
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/etc/bash_completion.d"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/zsh/site-functions"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/slv completion bash > #{HOMEBREW_PREFIX}/etc/bash_completion.d/slv"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/slv completion zsh > #{HOMEBREW_PREFIX}/share/zsh/site-functions/_slv"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/slv completion fish > #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/slv.fish"]
  end

  # No zap stanza required

end
